#
# IMPORTANT NOTE
#
# This chart inherits from k8s-at-home common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: browserless/chrome
  # -- image tag
  tag: 1.46-puppeteer-1.20.0
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See [image docs](https://docs.browserless.io/docs/docker.html) for more details.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  # -- Node.js runtime arguments
  MAX_CONCURRENT_SESSIONS: 10
  # -- Setting to `true` starts instances of Chrome ready to use
  PREBOOT_CHROME: false
  # -- Setting to `true` serves the interactive debugger, but not allow it to handle `puppeteer.connect` calls
  DEMO_MODE: false
  # -- Restrict calls without a `token` query-string parameter. When present, browserless will reject any calls that don't have a matching token
  TOKEN:
  # -- Downloads from Chromium default to this directory
  WORKSPACE_DIR: /downloads

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 3000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  downloads:
    enabled: false
    mountPath: /downloads